### ISSUE TITLE
should work with multiline if statements that do not include then

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript-formatter#11]
```	if url.instr(".m3u8") >= 0
		return "hls"
	else if url.instr(".mpd") >= 0
		return "dash"
	else
		return "hls"
	end if```
should be formatted correctly; instead if without then is ignored/badly formatted.

**Comment by luis-soares-sky** [comment]
Single-line ifs without `then` are still a problem for the formatter's indentation. Is a fix still being considered?

**Comment by TwitchBronBron** [comment]
@luis-soares-sky just use `then`, problem solved! :P Just kidding. 

Yes a fix is definitely still being considered. I just added some more information in #13 about this.
