### ISSUE TITLE
Example for `keywordCaseOverride`?

### ISSUE THREAD

**Issue by philippe-elsass-deltatre** [rokucommunity/brighterscript-formatter#35]
Doc is leaving a number of settings without any example. 

How to I make keywords generally lowercase BUT operators uppercase (e.g. `AND`, `OR`)?

**Comment by philippe-elsass-deltatre** [comment]
From the source: `{ [id: string]: FormattingOptions['keywordCase'] }`

So doc could maybe have:

> ex: `{ "and": "upper", "or": "upper", "not": "upper" }`

**Comment by TwitchBronBron** [comment]
We should definitely update the docs. But to answer your question, you would do something like this:

```json
"keywordCase": "lower",
keywordCaseOverride": {
    "and": "upper",
    "or": "upper"
}
```
