### ISSUE TITLE
array in consequent does not format correctly

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript-formatter#43]
![image](https://user-images.githubusercontent.com/1214545/148094675-a06f04cd-23e7-4f36-b95a-f9359a30cdf8.png)

**Comment by TwitchBronBron** [comment]
I feel like I'm missing something. What's wrong about the formatting? What would you expect it to be?

**Comment by georgejecook** [comment]
oh, sorry mate - thought it was clear. :)

look at the next line - it indents incorrectly, then the end function is in the wrong place.

**Comment by TwitchBronBron** [comment]
Ok, so it seems to be triggered by that first array `["sa"]`. Just reproduced it using this code:

```brightscript
sub main()
    a = true ? [] : true
    print a
end sub
```
