### ISSUE TITLE
Auto-formatting breaking "for" loop that contains a minus sign

### ISSUE THREAD

**Issue by luis-soares-sky** [rokucommunity/brighterscript-formatter#48]
Versions affected: >= 2.26.0

We use the `"editor.formatOnSave": true,`. When saving, spaces are getting obliterated, which results in invalid code.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/57358121/151984984-8ea48814-1777-4ba4-87d3-31b6da29bf04.gif)

**Comment by TwitchBronBron** [comment]
Fixed by #49
