### ISSUE TITLE
inline functions cause indentation to become displaced

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript-formatter#52]
the following code cuases the formatter to lose an indent. the lines that cuase the issue are the nested functoin call, namely:

```
      return not gameStates.isFinal(gameState) and mc.collections.contains(broadcasters, function(b as mc.types.assocarray)
        return lCase(b.broadCasterDispalyName) = "tnt"
      end function)
```

```
  function isTNTBlackout()
      if m.item <> invalid and m.item.subType() = "Game"
      gameStates = new nba.models.GameState()
      gameState = m.item@.getGameState()
      broadcasters = m.item@.getAllTVBroadcasters()
      'FIXME(gcook): formatter bug here!!
      return not gameStates.isFinal(gameState) and mc.collections.contains(broadcasters, function(b as mc.types.assocarray)
        return lCase(b.broadCasterDispalyName) = "tnt"
      end function)
    end if
    return false
  end function
end class
end function
```

if the nested function is commented out, formatting works fine

**Comment by georgejecook** [comment]
@TwitchBronBron I've nailed this down - it doesn't like the `(param as type)` definition - that's what makes it fail

**Comment by TwitchBronBron** [comment]
So the formatter should be fixed to not crash on this, but I'm pretty sure that you can't give types to parameters in those anonymous functions. I think that's a syntax error when compiling on device?

**Comment by georgejecook** [comment]
ah perhaps - so.. this is a bslint error then :)coz I'm doing that to keep bslint happy... the plot thickens.

**Comment by georgejecook** [comment]
appears to be resolved.
